# Generated by Django 5.1.5 on 2025-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_vuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='flight_type',
            field=models.CharField(choices=[('N', 'Nacional'), ('I', 'Internacional')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
